version: "2"

services:

  db:
    build: ./server/docker/db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./server/logs/db:/var/log/mysql
      - ./server/data:/var/lib/mysql
    container_name: db

  web1:
    build: ./server/docker/web
    environment:
      - VIRTUAL_HOST=web1.loalhost
    ports:
      - "60001:80"
    volumes:
      - ./workspace/src:/var/www/html
      - ./server/logs/web1:/var/log/apache2
    working_dir: /var/www/html
    container_name: web1

  web2:
    build: ./server/docker/web
    environment:
      - VIRTUAL_HOST=web2.loalhost
    ports:
      - "60002:80"
    volumes:
      - ./workspace/src:/var/www/html
      - ./server/logs/web2:/var/log/apache2
    working_dir: /var/www/html
    container_name: web2

