version: "2"

services:

  db:
    build: ./server/docker/db
    environment:
      - TZ=JST-9
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#     - MYSQL_ROOT_PASSWORD=password
#     - MYSQL_USER: foo
#     - MYSQL_PASSWORD: bar
#     - MYSQL_DATABASE=testdb
    ports:
      - "60000:3306"
    volumes:
      - ./server/logs/db:/var/log/mysql
      - ./server/data:/var/lib/mysql
      - ./workspace/ddl:/docker-entrypoint-initdb.d
    container_name: db

  web:
    build: ./server/docker/web
    environment:
      - TZ=JST-9
      - VIRTUAL_HOST=web.loalhost
    ports:
      - "60001:80"
    volumes:
      - ./workspace/src:/var/www/html
      - ./server/logs/web:/var/log/apache2
    working_dir: /var/www/html
    container_name: web
