version: "2"
services:
  web:
    build: ./web
    ports:
      - "3000:80"
    links:
      - db
    volumes:
      - ../workspace/src:/var/www/html
      - ../workspace/logs/web:/var/log/apache2
    working_dir: /var/www/html
    container_name: web
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ../workspace/logs/db:/var/log/mysql
      - ../workspace/data:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: db

